        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 30 11:11:12 2018
        MODULE TRIDIAGONALMATRIXALGORITHM__genmod
          INTERFACE 
            SUBROUTINE TRIDIAGONALMATRIXALGORITHM(X,N,A,B,C,D)
              INTEGER(KIND=4) :: N
              REAL(KIND=16) :: D(N-1)
            END SUBROUTINE TRIDIAGONALMATRIXALGORITHM
          END INTERFACE 
        END MODULE TRIDIAGONALMATRIXALGORITHM__genmod
