        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 24 21:22:08 2017
        MODULE TRIDIAGONALMATRIXALGORITHM__genmod
          INTERFACE 
            SUBROUTINE TRIDIAGONALMATRIXALGORITHM(X,N,A,B,C,D)
              INTEGER(KIND=4) :: N
              COMPLEX(KIND=8) :: X(N-1)
              COMPLEX(KIND=8) :: A(N-1)
              COMPLEX(KIND=8) :: B(N-1)
              COMPLEX(KIND=8) :: C(N-1)
              REAL(KIND=8) :: D(N-1)
            END SUBROUTINE TRIDIAGONALMATRIXALGORITHM
          END INTERFACE 
        END MODULE TRIDIAGONALMATRIXALGORITHM__genmod
