        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 10 14:08:35 2017
        MODULE TRIDIAGONALMATRIXALGORITHM__genmod
          INTERFACE 
            SUBROUTINE TRIDIAGONALMATRIXALGORITHM(X,N,A,B,C,D)
              INTEGER(KIND=4) :: N
              REAL(KIND=16) :: D(N-1)
            END SUBROUTINE TRIDIAGONALMATRIXALGORITHM
          END INTERFACE 
        END MODULE TRIDIAGONALMATRIXALGORITHM__genmod
