        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 10 00:06:21 2017
        MODULE PREPARES_BEFORENEW_TRIDALGORITHM__genmod
          INTERFACE 
            SUBROUTINE PREPARES_BEFORENEW_TRIDALGORITHM(A,B,C,F,U,A_11, &
     &TAU,MAT,N_X,M_POV,P_POV,H)
              INTEGER(KIND=4) :: N_X
              REAL(KIND=16) :: F(1:N_X)
              REAL(KIND=16) :: U(1:N_X)
              REAL(KIND=16) :: TAU
              REAL(KIND=16) :: MAT(1:N_X)
              REAL(KIND=16) :: M_POV
              REAL(KIND=16) :: P_POV
              REAL(KIND=16) :: H
            END SUBROUTINE PREPARES_BEFORENEW_TRIDALGORITHM
          END INTERFACE 
        END MODULE PREPARES_BEFORENEW_TRIDALGORITHM__genmod
